pages/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'about/$', views.about_view, name='about'),
    url(r'contact/$', views.contact_view, name='contact'),
    url(r'faq/$', views.faq_view, name='faq'),
    url(r'profile/$', views.profile_view, name='profile'),
    url(r'dashboard/$', views.dashboard_view, name='dashboard'),
]

pomodoro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('accounts.urls')),
    url(r'^', include('pages.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^add$', views.add_new_task, name='add_task'),
    url(r'^list$', views.TaskListView.as_view(), name='task_list'),
    url(r'^(?P<slug>[-\w]+)$', views.TaskDetailView.as_view(), name='task_detail'),
    url(r'^(?P<slug>[-\w]+)/delete_task$', views.delete_selected_task, name='task_delete'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/delete_note$', views.delete_selected_note, name='note_delete'),
]

tasks/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.conf import settings

class Task(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)  # set the slug explicitly
        super(Task, self).save(*args, **kwargs)  # call Django's save()


class Note(models.Model):
    task = models.ForeignKey(Task)
    name = models.CharField(max_length=50)
    note = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    url = models.URLField(blank=True)
    id = models.AutoField(primary_key=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.note


class Duration(models.Model):
    task = models.ForeignKey(Task)
    total_second = models.IntegerField(blank=True);
    started_at = models.TimeField(auto_now_add=True, blank=True, null=True)
    end_at = models.TimeField(auto_now_add=True, blank=True, null=True)

tasks/forms.py
from django.forms import ModelForm
from django import forms
from django.forms.models import inlineformset_factory

from .models import Task, Note, Duration

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name','description']


class NoteForm(ModelForm):
    class Meta:
        model = Note
        exclude = ['task',]
        fields = ['name', 'note', 'url']

class DurationForm(ModelForm):
    total_second = forms.IntegerField(required=True);

    class Meta:
        model = Duration
        fields =  ['total_second']

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic import FormView

from .models import Task, Note, Duration
from .forms import TaskForm, NoteForm, DurationForm

@login_required
def add_new_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.created_by = request.user # Get Current User
            obj.save()
            messages.success(request, 'Task has been successfully created')
            return redirect('task_list')
    else:
        form = TaskForm()
    return render(request, "tasks/add.html", {'form': form})


def task_for_user(user):
    return Task.objects.filter(created_by=user)


def delete_selected_task(request, slug):
    selected_task = get_object_or_404(Task, slug=slug)
    selected_task.delete()
    messages.success(request, 'Task has been successfully deleted')
    return redirect('task_list')


def delete_selected_note(request, pk, slug):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    selected_task = get_object_or_404(Task, slug=slug)
    messages.success(request, 'Note has been deleted')
#    return redirect('task_list')
    return HttpResponseRedirect(reverse('task_detail', kwargs={'slug':selected_task.slug}))


class TaskListView(generic.ListView):
    template_name = "tasks/task_list.html"
    context_object_name = "task_list"

    def get_queryset(self):
        #return Task.objects.filter(created_by=self.request.user)
        return task_for_user(self.request.user)

class TaskDetailView(FormMixin, generic.DetailView):
    model = Task
    template_name="tasks/detail.html"
    form_class = NoteForm
    form_class2 = DurationForm

    def get_context_data(self, **kwargs):
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        if 'note_form' not in context:
            context['note_form'] = self.get_form()
        if 'duration_form' not in context:
            context['duration_form'] = self.form_class2()
        # context['note_form'] = self.get_form()
        context['notes'] = Note.objects.filter(task__slug=self.kwargs['slug'])
        # context['duration_form'] = self.form_class2()
        #context['duration'] = Duration.objects.filter(task__slug=self.kwargs['slug'])
        context['durations'] = Duration.objects.all()
        return context

    def get_success_url(self):
       return reverse('task_detail', kwargs={'slug': self.kwargs['slug']})

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated: 
            return HttpResponseForbidden
        self.object = self.get_object()

        if 'note_form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'note_form'

        else:
            form_class = self.form_class2
            form_name = 'duration_form2'

        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        # form = self.get_form()
        # duration_form = self.form_class2(request.POST)
        # if form.is_valid() and duration_form.is_valid():
            # return self.form_valid(form, duration_form)
        # else:
            # return self.form_invalid(form, duration_form)

    def form_valid(self, form):
        """
        Called if all forms are valid. Creates a Task instance along with
        associated Notes and Duration and then redirects to a
        success page.
        """
        current_task = get_object_or_404(Task, slug=self.kwargs['slug'])
        self.object = form.save(commit=False)
        self.object.task = current_task
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
        # return HttpResponse(self.get_success_url())


    def form_invalid(self, form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        # return self.render_to_response(self.get_context_data(form=form, duration_form=duration_form))
        return self.render_to_response(self.get_context_data(form=form))

tasks/templates/tasks/add.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}TaskHive | Add Task{% endblock %}

{% block src %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/authenticated/add_task.css' %}">
{% endblock %}

{% block content %}

    <!--Mask-->
    <div class="view hm-black-strong">
        <div class="full-bg-img flex-center">
						<!--Form with header-->
						<div class="card">
								<div class="card-block">
										<!--Header-->
										<div class="form-header  purple darken-4">
												<h3><i class="fa fa-lock"></i> Login:</h3>
										</div>

										<!--Body-->
										<form id="login_form" method="POST" action="">{% csrf_token %}

												<div class="md-form">
													<i class="fa fa-envelope prefix"></i>
													<label for="name" data-error="wrong">Task Name</label>
													{{ form.name|add_class:"form-control validate" }}
												</div>

												<div class="md-form">
													<i class="material-icons prefix">mode_edit</i>
													<label for="description">Description</label>
													{{ form.description|add_class:"md-textarea validate" }}
												</div>

												<div class="text-xs-center">
														<button class="btn btn-deep-purple" type="submit" value="login">Login</button>
														<input type="hidden" name="next" value="{{ next }}" />
												</div>

										</form>

								</div>

								<!--Footer-->
								<div class="modal-footer">
										<div class="options">
											<p>Not a member? <a href="{% url 'register' %}">Sign Up</a></p>
												<!--<p>Forgot <a href="#">Password?</a></p>-->
										</div>
								</div>

						</div>
						<!--/Form with header-->
        </div>
    </div>
    <!--/.Mask-->

{% endblock %}

tasks/templates/tasks/detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block src %}
<link rel="stylesheet" type="text/css" href="{% static 'css/authenticated/task_detail.css' %}">
{% endblock %}

{% block content %}
    <div class="container margin red-text">

				<!-- Nav tabs -->
				<ul class="nav nav-tabs tabs-3 indigo" role="tablist">
						<li class="nav-item">
								<a class="nav-link waves-effect active" data-toggle="tab" href="#timer" role="tab"><i class="fa fa-user"></i> Timer</a>
						</li>
						<li class="nav-item">
								<a class="nav-link waves-effect" data-toggle="tab" href="#snippet" role="tab"><i class="fa fa-heart"></i> Snippets</a>
						</li>
						<li class="nav-item">
								<a class="nav-link waves-effect" data-toggle="tab" href="#tasks" role="tab"><i class="fa fa-envelope"></i> Task</a>
						</li>
				</ul>

				<!-- Tab panels -->
				<div class="tab-content">

						<!--Panel (Timer)-->
						<div class="tab-pane fade in active" id="timer" role="tabpanel">
								<br>

								<div class="">
										<div class="row">
												<div class="col-md-8">
														<div class="text-xs-center">
																<div id="instruction-container" class="">
																	<label id="minutes">00</label>:<label id="seconds">00</label>
																</div>
																<div id="time-container" class="hidden">
																	{% for duration in durations %}
																		{{ duration.total_second }}
																		{{ duration.started_at }}
																	{% endfor %}
																	<form method="POST">{% csrf_token %}
																		{{ duration_form }}

																	<div class="text-xs-center">
																		<button id="submit_snippet" class="btn btn-elegant btn-rounded wavewaves-effect" type="submit" name="duration_form" value="submit">Add Duration</button>
																	</div>
																	</form>
																</div>
														</div>
												</div>
												<div class="col-md-4">
													<div class="row">
														<div class="text-xs-center">
															<button id="start" class="btn btn-primary-outline btn-rounded waves-effect waves-blue" onclick="startTime()">Start</button>
															<button id="stop" class="btn btn-danger-outline btn-rounded waves-effect" onclick="pauseTime()">Stop/Pause</button>
														</div>
													</div>
													<hr class="section-divider">
													<div class="row">
														<div class="text-xs-center">
															<h1>Time</h1>
															<button id="add" class="btn-floating btn-small teal waves-effect"><i class="fa fa-plus"></i></button>
															<button id="subtract" class="btn-floating btn-small red waves-effect"><i class="fa fa-minus"></i></button>
															<h1><span id="select-number">0</span> minutes</h1>
														</div>
													</div>
												</div>
										</div>
								</div>

						</div>
						<!--/.Panel (Timer)-->

						<!--Panel (Snippets)-->
						<div class="tab-pane fade in" id="snippet" role="tabpanel">
								<br>
							<div class="container">
							  <!-- Notes -->
							  <ul id="snippet_list" class="collapsible" data-collapsible="accordion">
								{% for note in notes %}
								<li>
								  <div class="collapsible-header">
									<i class="material-icons">whatshot</i>
									<b>{{ note.name }}</B>
									<a href="{% url 'note_delete' pk=note.pk slug=task.slug %}" class="secondary-content"><i class="material-icons">delete</i></a>
								  </div>
								  <div class="collapsible-body">
									<div class="collapsible-content">
									  <div class="container">
										<div class="note-content">
										  {{ note.note }}
										</div>
										{% if note.url %}
										  <hr>
										  <div class="note-url">
											<a href="{{ note.url }}">{{ note.url }}</a>
										  </div>
										{% endif %}
									  </div>
									</div>
								  </div>
								</li>
								{% endfor %}
							  </ul>
							  <form id="snippet_form" class="col m12" method="POST">{% csrf_token %}
								<div class="row">

									  <div class="row"> <div class="input-field col s6"> <i class="material-icons prefix">subject</i>
										  <label for="last_name">Title</label>
										  {{ note_form.name }}
										</div>

										<div class="input-field col m12">
										  <i class="material-icons prefix">mode_edit</i>
										  <label for="description">Snippet</label>
										  {{ note_form.note|add_class:"md-textarea" }}
										</div>

									  <div class="input-field col m12">
										  <i class="material-icons prefix">https</i>
										  <!--<label for="description">URLs</label>-->
															<span class="input-group-addon" id="basic-addon3">https://</span>
										  {{ note_form.url|add_class:"form-control" }}
															<!--<input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">-->
										</div>
									  </div> <!-- Row -->

										<div class="text-xs-center">
											<button id="submit_snippet" class="btn btn-elegant btn-rounded wavewaves-effect" type="submit" name="note_form" value="submit">Add Snippet</button>
										</div>
									</div>
								  </form>

						</div>
						</div>
						<!--/.Panel (Snippets)-->
<!--Panel (Tasks)-->
						<div class="tab-pane fade" id="tasks" role="tabpanel">
							<br>

							<div class="jumbotron">
								<h1 class="h1-responsive"><b>{{ task }}<b></h1>
								<h3 class="lead"><i>{{ task.description }}</i></h3>
								<hr class="m-y-2">
								<p>Created on <b>{{ task.created_at }}<b></p>
								<p class="lead">
									<div class="text-xs-center">
										<a class="btn btn-primary btn-lg" href="{% url 'task_delete' slug=task.slug %}" class="link-text">Delete</a>
									</div>
								</p>
							</div>

						</div>
						<!--/.Panel (Tasks)-->

				</div>
		</div>

		<script src="{% static 'js/timer.js' %}"></script>
		<script>
//			$("document").on('submit', '#snippet_form', function(e) {
		//	$("#submit_snippet").on('click', function(e) {

				var minutesLabel = document.getElementById("minutes");
				var secondsLabel = document.getElementById("seconds");
				var totalSeconds = 0;
				var durationInterval;

				function setTime()
				{
					++totalSeconds;
					secondsLabel.innerHTML = pad(totalSeconds%60);
					minutesLabel.innerHTML = pad(parseInt(totalSeconds/60));
				}

				function startTime() {
					durationInterval = setInterval(setTime, 1000);
				}

				function pauseTime()  {
					clearInterval(durationInterval);
				}

				function pad(val)
				{
					var valString = val + "";
					if(valString.length < 2)
					{
						return "0" + valString;
					}
					else
					{
						return valString;
					}
				}



/*
			$('#snippet_form').on('submit', function(event){
				event.preventDefault();
				var name = $('#id_name').val();
				var snippet = $('#id_note').val();
				var url = $('#id_url').val();
				var form = $('#snippet_form');
				console.log("submit");
				var href = $(this).attr('href'); //Referring the anchor object which is clicked
				$.ajax({
					type: 'POST',
					url: href,
					data: form.serialize(),
					success: function(data) {
						console.log("Created new snippet");
						$("#snippet_list").prepend("<li><div class='collapsible-header'>\
								<i class='material-icons'>whatshot</i>\
								<b>"+name+"</b>\
							</div>\
							</li>"
						);
					},
					error: function(jqXHR, textStatus, errorThrown) {
					  alert(errorThrown);
				    }
				})
			})
*/

			$("document").ready(function() {

				setInterval(function() {
					currentTime = new Date();
					$("#current_time").text(currentTime);

					$("#duration").text();
				}, 1000)

				/* */

				var number = 0;

				$("#add").on('click', function() {
					number += 5;
					if (number > 60) {
						number = 60;
						$("#select-number").text(number);
					}
					else {
						$("#select-number").text(number);
					}
				})

				$("#subtract").on('click', function() {
					number -= 5;
					if (number < 0) {
						number = 0;
						$("#select-number").text(number);
					}
					else {
						$("#select-number").text(number);
					}
				})

				$("#start").on('click', function() {
					$("#time").time("start", number)
				})

				$("#stop").on('click', function() {
					$("#time").time("stop", number)
				})
			})
		</script>

{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% load static %}

{% block src %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/authenticated/task_list.css' %}">
{% endblock %}

{% block content %}
    <!--Mask-->
    <!--<div class="view hm-black-strong teal-text ">-->
        <!--<div class="full-bg-img">-->

			<!-- Ordering by favourite Tasks -->
			<section class="margin">
				<div class="container">
					<h1 class="h1-responsive"><b>Favourites</b></h1>
				  <div class="row">

					<div class="col-sm-4">
					  One of three columns
					</div>

					<div class="col-sm-4">
					  One of three columns
					</div>

					<div class="col-sm-4">
					  One of three columns
					</div>

				  </div>
				</div>
			</section>

			<hr class="section-divider container">

			<!-- Ordering by newest Tasks -->
			<section class="teal-text">
				<div class="container">
					<h1 class="h1-responsive"><b>Latest</b></h1>
					<div class="row">

					{% for task in task_list %}

					<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
						<!--Card-->
						<div class="card ovf-hidden">

							<!--Card image-->
							<!--<div class="view overlay hm-white-slight">-->
								<!--<img src="http://mdbootstrap.com/images/reg/reg%20(60).jpg" class="img-fluid" alt="">-->
								<!--<a>-->
									<!--<div class="mask"></div>-->
								<!--</a>-->
							<!--</div>-->
							<!--/.Card image-->

							<!--Social shares button-->
							<a class="activator"><i class="fa fa-share-alt"></i></a>

							<!--Card content-->
							<div class="card-block">
								<!--Title-->
								<h4 class="card-title h4-responsive">{{ task }}</h4>
								<hr>
								<!--Text-->
								<p class="card-text">{{ task.description }}</p>
								<a href="{% url 'task_detail' slug=task.slug %}" class="link-text"><h5>Details<i class="fa fa-chevron-right"></i></h5></a>
							</div>
							<!--/.Card content-->

							<!--Card reveal-->
							<div class="card-reveal">
								<!--Content-->
								<div class="content text-xs-center">

									<h4 class="card-title">Social shares <i class="fa fa-close"></i></h4>
									<hr>

									<!--Social Icons-->
									<ul class="inline-ul">
										<li><a class="btn-floating btn-small btn-fb"><i class="fa fa-facebook"> </i></a></li>
										<li><a class="btn-floating btn-small btn-tw"><i class="fa fa-twitter"> </i></a></li>
										<li><a class="btn-floating btn-small btn-gplus"><i class="fa fa-google-plus"> </i></a></li>
										<li><a class="btn-floating btn-small btn-li"><i class="fa fa-linkedin"> </i></a></li>
										<li><a class="btn-floating btn-small btn-git"><i class="fa fa-github"> </i></a></li>
										<li><a class="btn-floating btn-small btn-pin"><i class="fa fa-pinterest"> </i></a></li>
										<li><a class="btn-floating btn-small btn-ins"><i class="fa fa-instagram"> </i></a></li>
									</ul>

									<h5>Join our community</h5>
									<hr>

									  <a href="{% url 'task_delete' slug=task.slug %}" class="link-text">Delete</a>

									<!--Social Icons-->
									<ul class="inline-ul">
										<li><a class="btn btn-fb"><i class="fa fa-facebook"> </i></a></li>
										<li><a class="btn btn-tw"><i class="fa fa-twitter"> </i></a></li>
										<li><a class="btn btn-li"><i class="fa fa-linkedin"> </i></a></li>
										<li><a class="btn btn-ins"><i class="fa fa-instagram"> </i></a></li>
									</ul>

								</div>
								<!--/.Content-->

							</div>
							<!--/.Card reveal-->

						</div>
						<!--/.Card-->
					</div>
					{% endfor %}

				  </div>

				</div>
			</section>

        <!--</div>-->
    <!--</div>-->
    <!--/.Mask-->

	<script>
		$("document").ready(function() {
			$('.button-collapse').sideNav('show');
		})
	</script>

{% endblock %}